'use strict';function v(h,a,b,c){h.A.dc(h.Qa,a,b,c,void 0)}function z(h,a,b,c){h.A.Ja?v(h,a,b,c):h.A.af()._OnMessageFromDOM({type:"event",component:h.Qa,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function A(h,a,b){h.A.B(h.Qa,a,b)}function B(h,a){for(const [b,c]of a)A(h,b,c)}function C(h){h.Ib||(h.A.Me(h.Td),h.Ib=!0)}window.kb=class{constructor(h,a){this.A=h;this.Qa=a;this.Ib=!1;this.Td=()=>this.qa()}Xc(){}qa(){}};function D(h){-1!==h.Ia&&(self.clearTimeout(h.Ia),h.Ia=-1)}
window.De=class{constructor(h,a){this.Bc=h;this.og=a;this.Ia=-1;this.Jb=-Infinity;this.Ud=()=>{this.Ia=-1;this.Jb=Date.now();this.Va=!0;this.Bc();this.Va=!1};this.Cd=this.Va=!1}c(){D(this);this.Ud=this.Bc=null}};"use strict";function E(h,a){A(h,"get-element",b=>{const c=h.ca.get(b.elementId);return a(c,b)})}
window.Hg=class extends self.kb{constructor(h,a){super(h,a);this.ca=new Map;this.Ac=!0;B(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const c=this.ca.get(b);this.Ac&&c.parentElement.removeChild(c);this.ca.delete(b)}}],["set-visible",b=>{this.Ac&&(this.ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Ac){var c=this.ca.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=
b.height+"px";b=b.fontSize;null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{this.ca.get(b.elementId);throw Error("required override");}],["focus",b=>{{const c=this.ca.get(b.elementId);b.focus?c.focus():c.blur()}}],["set-css-style",b=>{this.ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ca.get(b.elementId).removeAttribute(b.name)}]]);E(this,b=>b)}};"use strict";
{var F=function(q){return l.has(q)},G=function(q){return new Promise((e,k)=>{const m=new FileReader;m.onload=r=>e(r.target.result);m.onerror=r=>k(r);m.readAsArrayBuffer(q)})},H=async function(q){q=await G(q);return(new TextDecoder("utf-8")).decode(q)},I=function(q){if(q.yg){const e=document.createElement("script");e.async=!1;e.textContent=q.Bg;document.head.appendChild(e)}else return new Promise((e,k)=>{const m=document.createElement("script");m.onload=e;m.onerror=k;m.async=!1;m.src=q;document.head.appendChild(m)})};
const h=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=new Audio;const b={"audio/webm; codecs=opus":!!a.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!a.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!a.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!a.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!a.canPlayType("audio/mp4"),"audio/mpeg":!!a.canPlayType("audio/mpeg")};a=null;const c=[];let f=0;window.RealFile=
window.File;const p=[],t=new Map,d=new Map;let g=0;const n=[];self.Mg=function(q){if("function"!==typeof q)throw Error("runOnStartup called without a function");n.push(q)};const l=new Set(["cordova","playable-ad","instant-games"]);window.qb=class q{constructor(e){this.Ja=e.Dg;this.ma=null;this.V="";this.Rc=e.Ag;this.jb={};this.Ba=this.ib=null;this.Gb=[];this.Xa=this.I=this.Ga=null;this.Fa=-1;this.tg=()=>this.zf();this.Ea=[];this.W=e.Vd;F(this.W)&&this.Ja&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.Ja=!1);this.Uc=!1;this.Lb=this.ha=null;"html5"!==this.W&&"playable-ad"!==this.W||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.B("runtime","cordova-fetch-local-file",k=>this.jf(k));this.B("runtime","create-job-worker",()=>this.kf());"cordova"===this.W?document.addEventListener("deviceready",()=>this.qd(e)):this.qd(e)}c(){this.kc();this.ma&&
(this.ma=this.ma.onmessage=null);this.ib&&(this.ib.terminate(),this.ib=null);this.Ba&&(this.Ba.c(),this.Ba=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}dd(){return h&&"cordova"===this.W}ob(){return h&&F(this.W)||navigator.standalone}async qd(e){if("playable-ad"===this.W){this.ha=self.c3_base64files;this.Lb={};await this.Re();for(let m=0,r=e.Ka.length;m<r;++m){var k=e.Ka[m].toLowerCase();this.Lb.hasOwnProperty(k)?e.Ka[m]={yg:!0,Bg:this.Lb[k]}:this.ha.hasOwnProperty(k)&&(e.Ka[m]=
URL.createObjectURL(this.ha[k]))}}e.vg?this.V=e.vg:(k=location.origin,this.V=("null"===k?"file:///":k)+location.pathname,k=this.V.lastIndexOf("/"),-1!==k&&(this.V=this.V.substr(0,k+1)));if(e.Fg)for(const [m,r]of Object.entries(e.Fg))this.jb[m]=URL.createObjectURL(r);k=new MessageChannel;this.ma=k.port1;this.ma.onmessage=m=>this._OnMessageFromRuntime(m.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(m=>this.vf(m));this.Xa=new self.ze(this);await this.Xa.ve();this.ed();"object"===
typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this.hg();this.Ja?await this.cf(e,k.port2):await this.bf(e,k.port2)}nc(e){return this.jb.hasOwnProperty(e)?this.jb[e]:e.endsWith("/workermain.js")&&this.jb.hasOwnProperty("workermain.js")?this.jb["workermain.js"]:"playable-ad"===this.W&&this.ha.hasOwnProperty(e.toLowerCase())?URL.createObjectURL(this.ha[e.toLowerCase()]):e}async Xb(e,k,m){if(e.startsWith("blob:"))return new Worker(e,
m);if(this.dd()&&"file:"===location.protocol)return e=await this.Wb(this.Rc+e),new Worker(URL.createObjectURL(new Blob([e],{type:"application/javascript"})),m);e=new URL(e,k);if(location.origin!==e.origin){e=await fetch(e);if(!e.ok)throw Error("failed to fetch worker script");e=await e.blob();return new Worker(URL.createObjectURL(e),m)}return new Worker(e,m)}ed(){if(this.ob()){const e=document.documentElement.style,k=document.body.style,m=window.innerWidth<window.innerHeight,r=m?window.screen.width:
window.screen.height;k.height=e.height=(m?window.screen.height:window.screen.width)+"px";k.width=e.width=r+"px"}}pd(e){return{baseUrl:this.V,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:q.cc(),projectData:e.Lg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:e.Vd,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Kg,jobScheduler:this.Xa.te(),
supportedAudioFormats:b,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Rc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Rc+"opus.wasm.wasm",isiOSCordova:this.dd(),isiOSWebView:this.ob(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async cf(e,k){var m=this.nc(e.Eg);this.ib=await this.Xb(m,this.V,{name:"Runtime"});this.I=document.createElement("canvas");this.I.style.display="none";m=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=
this.I;this.ib.postMessage(Object.assign(this.pd(e),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:m,workerDependencyScripts:e.Wc||[],engineScripts:e.Ka,projectScripts:window.Jg,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,m,...this.Xa.ue()]);this.Gb=p.map(r=>new r(this));this.od();self.c3_callFunction=(r,u)=>this.Ga.df(r,u);"preview"===this.W&&(self.goToLastErrorScript=()=>this.dc("runtime","go-to-last-error-script"))}async bf(e,k){this.I=document.createElement("canvas");this.I.style.display=
"none";document.body.appendChild(this.I);window.c3canvas=this.I;this.Gb=p.map(r=>new r(this));this.od();const m=e.Ka.map(r=>"string"===typeof r?(new URL(r,this.V)).toString():r);Array.isArray(e.Wc)&&m.unshift(...e.Wc);await Promise.all(m.map(r=>I(r)));if(e.Wd&&0<e.Wd.length){const r=self.C3_ProjectScriptsStatus;try{if(await Promise.all(e.Wd.map(u=>I(u[1]))),Object.values(r).some(u=>!u)){self.setTimeout(()=>this.xd(r),100);return}}catch(u){console.error("[Preview] Error loading project scripts: ",
u);self.setTimeout(()=>this.xd(r),100);return}}"preview"===this.W&&"object"!==typeof self.Gg.Ig?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(e=Object.assign(this.pd(e),{isInWorker:!1,messagePort:k,canvas:this.I,runOnStartupFunctions:n}),this.Ba=self.C3_CreateRuntime(e),await self.C3_InitRuntime(this.Ba,e))}xd(e){e=
`Failed to load project script '${Object.entries(e).filter(k=>!k[1]).map(k=>k[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+e);alert(e)}async kf(){const e=await this.Xa.nd();return{outputPort:e,transferables:[e]}}af(){if(this.Ja)throw Error("not available in worker mode");return this.Ba}dc(e,k,m,r,u){this.ma.postMessage({type:"event",component:e,handler:k,dispatchOpts:r||null,data:m,responseId:null},this.Uc?void 0:u)}fd(e,k,m,r,u){const x=g++,w=new Promise((y,
S)=>{d.set(x,{resolve:y,reject:S})});this.ma.postMessage({type:"event",component:e,handler:k,dispatchOpts:r||null,data:m,responseId:x},this.Uc?void 0:u);return w}["_OnMessageFromRuntime"](e){const k=e.type;if("event"===k)return this.qf(e);if("result"===k)this.Cf(e);else if("runtime-ready"===k)this.Df();else if("alert"===k)alert(e.message);else throw Error(`unknown message '${k}'`);}qf(e){const k=e.component,m=e.handler,r=e.data,u=e.responseId;if(e=t.get(k))if(e=e.get(m)){var x=null;try{x=e(r)}catch(w){console.error(`Exception in '${k}' handler '${m}':`,
w);null!==u&&this.zb(u,!1,""+w);return}if(null===u)return x;x&&x.then?x.then(w=>this.zb(u,!0,w)).catch(w=>{console.error(`Rejection from '${k}' handler '${m}':`,w);this.zb(u,!1,""+w)}):this.zb(u,!0,x)}else console.warn(`[DOM] No handler '${m}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}zb(e,k,m){let r;m&&m.transferables&&(r=m.transferables);this.ma.postMessage({type:"result",responseId:e,isOk:k,result:m},r)}Cf(e){const k=e.responseId,m=e.isOk;e=e.result;
const r=d.get(k);m?r.resolve(e):r.reject(e);d.delete(k)}B(e,k,m){let r=t.get(e);r||(r=new Map,t.set(e,r));if(r.has(k))throw Error(`[DOM] Component '${e}' already has handler '${k}'`);r.set(k,m)}static Ub(e){if(p.includes(e))throw Error("DOM handler already added");p.push(e)}od(){for(const e of this.Gb)if("runtime"===e.Qa){this.Ga=e;return}throw Error("cannot find runtime DOM handler");}vf(e){this.dc("debugger","message",e)}Df(){for(const e of this.Gb)e.Xc()}static cc(){return!!(document.fullscreenElement||
document.webkitFullscreenElement||document.mozFullScreenElement)}Me(e){this.Ea.push(e);this.yc()}Of(e){e=this.Ea.indexOf(e);if(-1===e)throw Error("invalid callback");this.Ea.splice(e,1);this.Ea.length||this.kc()}yc(){-1===this.Fa&&this.Ea.length&&(this.Fa=requestAnimationFrame(this.tg))}kc(){-1!==this.Fa&&(cancelAnimationFrame(this.Fa),this.Fa=-1)}zf(){this.Fa=-1;for(const e of this.Ea)e();this.yc()}ra(e){this.Ga.ra(e)}xa(e){this.Ga.xa(e)}xc(){this.Ga.xc()}sb(e){this.Ga.sb(e)}xe(){return!!b["audio/webm; codecs=opus"]}async mg(e){e=
await this.fd("runtime","opus-decode",{arrayBuffer:e},null,[e]);return new Float32Array(e)}we(e){return/^(?:[a-z]+:)?\/\//.test(e)||"data:"===e.substr(0,5)||"blob:"===e.substr(0,5)}ye(e){return!this.we(e)}async jf(e){const k=e.filename;switch(e.as){case "text":return await this.me(k);case "buffer":return await this.Wb(k);default:throw Error("unsupported type");}}$c(e){const k=window.cordova.file.applicationDirectory+"www/"+e.toLowerCase();return new Promise((m,r)=>{window.resolveLocalFileSystemURL(k,
u=>{u.file(m,r)},r)})}async me(e){e=await this.$c(e);return await H(e)}lc(){if(c.length&&!(8<=f)){f++;var e=c.shift();this.Se(e.filename,e.Cg,e.xg)}}Wb(e){return new Promise((k,m)=>{c.push({filename:e,Cg:r=>{f--;this.lc();k(r)},xg:r=>{f--;this.lc();m(r)}});this.lc()})}async Se(e,k,m){try{const r=await this.$c(e),u=await G(r);k(u)}catch(r){m(r)}}async Re(){const e=[];for(const [k,m]of Object.entries(this.ha))e.push(this.Qe(k,m));await Promise.all(e)}async Qe(e,k){if("object"===typeof k)this.ha[e]=
new Blob([k.str],{type:k.type}),this.Lb[e]=k.str;else{let m=await this.Ze(k);m||(m=this.Ue(k));this.ha[e]=m}}async Ze(e){try{return await (await fetch(e)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}Ue(e){e=this.If(e);return this.Pe(e.data,e.zg)}If(e){var k=e.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");
var m=e.substring(k+1);k=e.substring(5,k).split(";");e=k[0]||"";const r=k[2];m="base64"===k[1]||"base64"===r?atob(m):decodeURIComponent(m);return{zg:e,data:m}}Pe(e,k){var m=e.length;let r=m>>2,u=new Uint8Array(m),x=new Uint32Array(u.buffer,0,r),w,y;for(y=w=0;w<r;++w)x[w]=e.charCodeAt(y++)|e.charCodeAt(y++)<<8|e.charCodeAt(y++)<<16|e.charCodeAt(y++)<<24;for(m&=3;m--;)u[y]=e.charCodeAt(y),++y;return new Blob([u],{type:k})}hg(){let e=null;const k=new Promise(u=>e=u),m=new ArrayBuffer(1),r=new MessageChannel;
r.port2.onmessage=u=>{u.data&&u.data.arrayBuffer||(this.Uc=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));e()};r.port1.postMessage({arrayBuffer:m},[m]);return k}}}"use strict";
{var K=function(){const d=document.activeElement;if(!d)return!1;const g=d.tagName.toLowerCase(),n=new Set("email number password search tel text url".split(" "));return"textarea"===g?!0:"input"===g?n.has(d.type.toLowerCase()||"text"):J(d)},L=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(d){return!1}},M=function(d){(d.metaKey||d.ctrlKey)&&d.preventDefault()},N=function(d){p.has(d.target.tagName.toLowerCase())&&d.preventDefault()},J=function(d){do{if(d.parentNode&&d.hasAttribute("contenteditable"))return!0;
d=d.parentNode}while(d);return!1},Q=async function(d,g,n){if(!/firefox/i.test(navigator.userAgent))return await O(d);var l=await P(d);l=(new DOMParser).parseFromString(l,"image/svg+xml");const q=l.documentElement;if(q.hasAttribute("width")&&q.hasAttribute("height")){const e=q.getAttribute("width"),k=q.getAttribute("height");if(!e.includes("%")&&!k.includes("%"))return await O(d)}q.setAttribute("width",g+"px");q.setAttribute("height",n+"px");l=(new XMLSerializer).serializeToString(l);d=new Blob([l],
{type:"image/svg+xml"});return await O(d)},P=function(d){return new Promise((g,n)=>{let l=new FileReader;l.onload=q=>g(q.target.result);l.onerror=q=>n(q);l.readAsText(d)})},O=async function(d){d=URL.createObjectURL(d);try{return await R(d)}finally{URL.revokeObjectURL(d)}},R=function(d){return new Promise((g,n)=>{const l=new Image;l.onload=()=>g(l);l.onerror=q=>n(q);l.src=d})},T=function(d){return new Promise((g,n)=>{const l=document.createElement("link");l.onload=()=>g(l);l.onerror=q=>n(q);l.rel=
"stylesheet";l.href=d;document.head.appendChild(l)})},U=function(d){return d.sourceCapabilities&&d.sourceCapabilities.firesTouchEvents||d.originalEvent&&d.originalEvent.sourceCapabilities&&d.originalEvent.sourceCapabilities.firesTouchEvents};const h=self.qb,a=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),b={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},c={dispatchUserScriptEvent:!0},f={dispatchRuntimeEvent:!0},p=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(d){d=
await O(d);if(0<d.width&&0<d.height)return[d.width,d.height];{d.style.position="absolute";d.style.left="0px";d.style.top="0px";d.style.visibility="hidden";document.body.appendChild(d);const g=d.getBoundingClientRect();document.body.removeChild(d);return[g.width,g.height]}};self.C3_RasterSvgImageBlob=async function(d,g,n,l,q){d=await Q(d,g,n);const e=document.createElement("canvas");e.width=l;e.height=q;e.getContext("2d").drawImage(d,0,0,g,n);return e};let t=!1;document.addEventListener("pause",()=>
t=!0);document.addEventListener("resume",()=>t=!1);h.Ub(class extends self.kb{constructor(d){super(d,"runtime");this.Hd=!0;this.Ha=-1;this.Sc="any";this.yd=this.zd=!1;this.Lc=this.fb=this.ta=null;d.B("canvas","update-size",l=>this.Gf(l));d.B("runtime","invoke-download",l=>this.tf(l));d.B("runtime","raster-svg-image",l=>this.Af(l));d.B("runtime","get-svg-image-size",l=>this.sf(l));d.B("runtime","set-target-orientation",l=>this.Ef(l));d.B("runtime","register-sw",()=>this.Bf());d.B("runtime","post-to-debugger",
l=>this.td(l));d.B("runtime","go-to-script",l=>this.td(l));d.B("runtime","before-start-ticking",()=>this.hf());d.B("runtime","debug-highlight",l=>this.lf(l));d.B("runtime","enable-device-orientation",()=>this.Oe());d.B("runtime","enable-device-motion",()=>this.Ne());d.B("runtime","add-stylesheet",l=>this.ff(l));d.B("runtime","alert",l=>this.gf(l));const g=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",l=>{const q=l.target;g.has(q.tagName.toLowerCase())||J(q)||l.preventDefault()});
const n=d.I;window.addEventListener("selectstart",N);window.addEventListener("gesturehold",N);n.addEventListener("selectstart",N);n.addEventListener("gesturehold",N);window.addEventListener("touchstart",N,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",N,{passive:!1}),n.addEventListener("pointerdown",N)):n.addEventListener("touchstart",N);this.bb=0;window.addEventListener("mousedown",l=>{1===l.button&&l.preventDefault()});window.addEventListener("mousewheel",
M,{passive:!1});window.addEventListener("wheel",M,{passive:!1});window.addEventListener("resize",()=>this.Hf());d.ob()&&window.addEventListener("focusout",()=>{K()||(document.scrollingElement.scrollTop=0)});this.Ca=new Set;this.Mb=new WeakSet;this.la=!1}hf(){"cordova"===this.A.W?(document.addEventListener("pause",()=>this.wc(!0)),document.addEventListener("resume",()=>this.wc(!1))):document.addEventListener("visibilitychange",()=>this.wc(document.hidden));return{isSuspended:!(!document.hidden&&!t)}}Xc(){window.addEventListener("focus",
()=>this.Ab("window-focus"));window.addEventListener("blur",()=>{this.Ab("window-blur",{parentHasFocus:L()});this.bb=0});window.addEventListener("fullscreenchange",()=>this.sc());window.addEventListener("webkitfullscreenchange",()=>this.sc());window.addEventListener("mozfullscreenchange",()=>this.sc());window.addEventListener("fullscreenerror",g=>this.tc(g));window.addEventListener("webkitfullscreenerror",g=>this.tc(g));window.addEventListener("mozfullscreenerror",g=>this.tc(g));window.addEventListener("keydown",
g=>this.sd("keydown",g));window.addEventListener("keyup",g=>this.sd("keyup",g));window.addEventListener("dblclick",g=>this.uc("dblclick",g,b));window.addEventListener("wheel",g=>this.xf(g));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",g=>{this.oc(g);this.Oa("pointerdown",g)}),this.A.Ja&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.fb=new self.De(()=>this.Xe(),5),this.fb.Cd=!0,window.addEventListener("pointerrawupdate",g=>this.yf(g))):window.addEventListener("pointermove",
g=>this.Oa("pointermove",g)),window.addEventListener("pointerup",g=>this.Oa("pointerup",g)),window.addEventListener("pointercancel",g=>this.Oa("pointercancel",g))):(window.addEventListener("mousedown",g=>{this.oc(g);this.vc("pointerdown",g)}),window.addEventListener("mousemove",g=>this.vc("pointermove",g)),window.addEventListener("mouseup",g=>this.vc("pointerup",g)),window.addEventListener("touchstart",g=>{this.oc(g);this.yb("pointerdown",g)}),window.addEventListener("touchmove",g=>this.yb("pointermove",
g)),window.addEventListener("touchend",g=>this.yb("pointerup",g)),window.addEventListener("touchcancel",g=>this.yb("pointercancel",g)));const d=()=>this.xc();window.addEventListener("pointerup",d,!0);window.addEventListener("touchend",d,!0);window.addEventListener("click",d,!0);window.addEventListener("keydown",d,!0);window.addEventListener("gamepadconnected",d,!0)}Ab(d,g){v(this,d,g||null,f)}wb(){return Math.max(window.innerWidth,1)}vb(){return Math.max(window.innerHeight,1)}Hf(){const d=this.wb(),
g=this.vb();this.Ab("window-resize",{innerWidth:d,innerHeight:g,devicePixelRatio:window.devicePixelRatio});this.A.ob()&&(-1!==this.Ha&&clearTimeout(this.Ha),this.ud(d,g,0))}Pf(d,g,n){-1!==this.Ha&&clearTimeout(this.Ha);this.Ha=setTimeout(()=>this.ud(d,g,n),48)}ud(d,g,n){const l=this.wb(),q=this.vb();this.Ha=-1;l!=d||q!=g?this.Ab("window-resize",{innerWidth:l,innerHeight:q,devicePixelRatio:window.devicePixelRatio}):10>n&&this.Pf(l,q,n+1)}Ef(d){this.Sc=d.targetOrientation}ig(){const d=this.Sc;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(d).catch(g=>console.warn("[Construct 3] Failed to lock orientation: ",g));else try{let g=!1;screen.lockOrientation?g=screen.lockOrientation(d):screen.webkitLockOrientation?g=screen.webkitLockOrientation(d):screen.mozLockOrientation?g=screen.mozLockOrientation(d):screen.msLockOrientation&&(g=screen.msLockOrientation(d));g||console.warn("[Construct 3] Failed to lock orientation")}catch(g){console.warn("[Construct 3] Failed to lock orientation: ",g)}}sc(){const d=
h.cc();d&&"any"!==this.Sc&&this.ig();v(this,"fullscreenchange",{isFullscreen:d,innerWidth:this.wb(),innerHeight:this.vb()})}tc(d){console.warn("[Construct 3] Fullscreen request failed: ",d);v(this,"fullscreenerror",{isFullscreen:h.cc(),innerWidth:this.wb(),innerHeight:this.vb()})}wc(d){d?this.A.kc():this.A.yc();v(this,"visibilitychange",{hidden:d})}sd(d,g){"Backspace"===g.key&&N(g);const n=a.get(g.code)||g.code;z(this,d,{code:n,key:g.key,which:g.which,repeat:g.repeat,altKey:g.altKey,ctrlKey:g.ctrlKey,
metaKey:g.metaKey,shiftKey:g.shiftKey,timeStamp:g.timeStamp},b)}xf(d){v(this,"wheel",{clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,deltaX:d.deltaX,deltaY:d.deltaY,deltaZ:d.deltaZ,deltaMode:d.deltaMode,timeStamp:d.timeStamp},b)}uc(d,g,n){U(g)||z(this,d,{button:g.button,buttons:g.buttons,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,timeStamp:g.timeStamp},n)}vc(d,g){if(!U(g)){var n=this.bb;"pointerdown"===d&&0!==n?d="pointermove":"pointerup"===d&&0!==g.buttons&&
(d="pointermove");z(this,d,{pointerId:1,pointerType:"mouse",button:g.button,buttons:g.buttons,lastButtons:n,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:g.timeStamp},b);this.bb=g.buttons;this.uc(g.type,g,c)}}Oa(d,g){if(this.fb&&"pointermove"!==d){var n=this.fb;n.Va||(D(n),n.Jb=Date.now())}n=0;"mouse"===g.pointerType&&(n=this.bb);z(this,d,{pointerId:g.pointerId,pointerType:g.pointerType,button:g.button,
buttons:g.buttons,lastButtons:n,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,width:g.width||0,height:g.height||0,pressure:g.pressure||0,tangentialPressure:g.tangentialPressure||0,tiltX:g.tiltX||0,tiltY:g.tiltY||0,twist:g.twist||0,timeStamp:g.timeStamp},b);"mouse"===g.pointerType&&(n="mousemove","pointerdown"===d?n="mousedown":"pointerup"===d&&(n="pointerup"),this.uc(n,g,c),this.bb=g.buttons)}yf(d){this.Lc=d;d=this.fb;if(-1===d.Ia){var g=Date.now(),n=g-d.Jb,l=d.og;n>=l&&d.Cd?(d.Jb=
g,d.Va=!0,d.Bc(),d.Va=!1):d.Ia=self.setTimeout(d.Ud,Math.max(l-n,4))}}Xe(){this.Oa("pointermove",this.Lc);this.Lc=null}yb(d,g){for(let n=0,l=g.changedTouches.length;n<l;++n){const q=g.changedTouches[n];z(this,d,{pointerId:q.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:q.clientX,clientY:q.clientY,pageX:q.pageX,pageY:q.pageY,width:2*(q.radiusX||q.webkitRadiusX||0),height:2*(q.radiusY||q.webkitRadiusY||0),pressure:q.force||q.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,
twist:q.rotationAngle||0,timeStamp:g.timeStamp},b)}}oc(d){window!==window.top&&window.focus();this.rd(d.target)&&document.activeElement&&!this.rd(document.activeElement)&&document.activeElement.blur()}rd(d){return!d||d===document||d===window||d===document.body||"canvas"===d.tagName.toLowerCase()}Oe(){this.zd||(this.zd=!0,window.addEventListener("deviceorientation",d=>this.nf(d)),window.addEventListener("deviceorientationabsolute",d=>this.pf(d)))}Ne(){this.yd||(this.yd=!0,window.addEventListener("devicemotion",
d=>this.mf(d)))}nf(d){v(this,"deviceorientation",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp,webkitCompassHeading:d.webkitCompassHeading,webkitCompassAccuracy:d.webkitCompassAccuracy},b)}pf(d){v(this,"deviceorientationabsolute",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp},b)}mf(d){let g=null;var n=d.acceleration;n&&(g={x:n.x||0,y:n.y||0,z:n.z||0});n=null;var l=d.accelerationIncludingGravity;l&&(n={x:l.x||
0,y:l.y||0,z:l.z||0});l=null;const q=d.rotationRate;q&&(l={alpha:q.alpha||0,beta:q.beta||0,gamma:q.gamma||0});v(this,"devicemotion",{acceleration:g,accelerationIncludingGravity:n,rotationRate:l,interval:d.interval,timeStamp:d.timeStamp},b)}Gf(d){const g=this.A,n=g.I;n.style.width=d.styleWidth+"px";n.style.height=d.styleHeight+"px";n.style.marginLeft=d.marginLeft+"px";n.style.marginTop=d.marginTop+"px";g.ed();this.Hd&&(n.style.display="",this.Hd=!1)}tf(d){const g=d.url;d=d.filename;const n=document.createElement("a"),
l=document.body;n.textContent=d;n.href=g;n.download=d;l.appendChild(n);n.click();l.removeChild(n)}async Af(d){var g=d.imageBitmapOpts;d=await self.C3_RasterSvgImageBlob(d.blob,d.imageWidth,d.imageHeight,d.surfaceWidth,d.surfaceHeight);g=g?await createImageBitmap(d,g):await createImageBitmap(d);return{imageBitmap:g,transferables:[g]}}async sf(d){return await self.C3_GetSvgImageSize(d.blob)}async ff(d){await T(d.url)}xc(){var d=[...this.Ca];this.Ca.clear();if(!this.la)for(const g of d)(d=g.play())&&
d.catch(()=>{this.Mb.has(g)||this.Ca.add(g)})}ra(d){if("function"!==typeof d.play)throw Error("missing play function");this.Mb.delete(d);let g;try{g=d.play()}catch(n){this.Ca.add(d);return}g&&g.catch(()=>{this.Mb.has(d)||this.Ca.add(d)})}xa(d){this.Ca.delete(d);this.Mb.add(d)}sb(d){this.la=!!d}lf(d){if(d.show){this.ta||(this.ta=document.createElement("div"),this.ta.id="inspectOutline",document.body.appendChild(this.ta));var g=this.ta;g.style.display="";g.style.left=d.left-1+"px";g.style.top=d.top-
1+"px";g.style.width=d.width+2+"px";g.style.height=d.height+2+"px";g.textContent=d.name}else this.ta&&(this.ta.style.display="none")}Bf(){window.C3_RegisterSW&&window.C3_RegisterSW()}td(d){window.c3_postToMessagePort&&(d.from="runtime",window.c3_postToMessagePort(d))}df(d,g){return this.A.fd(this.Qa,"js-invoke-function",{name:d,params:g},void 0,void 0)}gf(d){alert(d.message)}})}"use strict";
{const h=document.currentScript.src;self.ze=class{constructor(a){this.Qb=a;this.V=h?h.substr(0,h.lastIndexOf("/")+1):a.V;this.qg=Math.min(navigator.hardwareConcurrency||2,16);this.Dc=null;this.Jd=[];this.Pc=this.Hc=null}async ve(){if(this.ng)throw Error("already initialised");this.ng=!0;var a=this.Qb.nc("dispatchworker.js");this.Dc=await this.Qb.Xb(a,this.V,{name:"DispatchWorker"});a=new MessageChannel;this.Hc=a.port1;this.Dc.postMessage({type:"_init","in-port":a.port2},[a.port2]);this.Pc=await this.nd()}async nd(){const a=
this.Jd.length;var b=this.Qb.nc("jobworker.js");b=await this.Qb.Xb(b,this.V,{name:"JobWorker"+a});const c=new MessageChannel,f=new MessageChannel;this.Dc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":f.port2},[c.port2,f.port2]);this.Jd.push(b);return f.port1}te(){return{inputPort:this.Hc,outputPort:this.Pc,maxNumWorkers:this.qg}}ue(){return[this.Hc,this.Pc]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.qb({Dg:"undefined"!==typeof OffscreenCanvas,Eg:"workermain.js",Ka:["scripts/c3runtime.js"],Ag:"scripts/",Wc:[],Vd:"html5"}));"use strict";async function V(h){var a=W(h.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:h.duration,startDelay:0,weakMagnitude:h.weakMag,strongMagnitude:h.strongMag})}catch(b){console.warn("[Gamepad] Failed to vibrate gamepad: ",b)}}
function X(){return Array.from(navigator.getGamepads()).filter(h=>h&&h.connected)}function W(h){for(const a of X())if(a.index===h)return a;return null}
self.qb.Ub(class extends self.kb{constructor(h){super(h,"gamepad");this.Id=!!navigator.getGamepads;this.Jc=!1;A(this,"is-supported",()=>this.Id);A(this,"ready",()=>{this.Jc=!0;for(const a of X())v(this,"gamepad-connected",{index:a.index,id:a.id});this.Id&&C(this)});A(this,"vibrate",a=>V(a));A(this,"reset-vibrate",a=>{(a=W(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.Jc&&(a=a.gamepad,v(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.Jc&&v(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of X()){const b=a.vibrationActuator;b&&b.reset&&b.reset()}})}qa(){var h=X();h.length&&(h=h.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(b=>({pressed:b.pressed,value:b.value})),axes:a.axes})),v(this,"input-update",h))}});"use strict";
{const h=180/Math.PI;self.da=class extends self.kb{constructor(a){super(a,"audio");this.Fb=this.f=null;this.Hb=this.Gc=!1;this.na=()=>this.jg();this.aa=[];this.C=[];this.ga=null;this.Kd="";this.Ld=-1;this.eb=new Map;this.Mc=1;this.la=!1;this.Tc=0;this.Sb=1;this.Ec=0;this.Nd="HRTF";this.Dd="inverse";this.Od=600;this.Md=1E4;this.Qd=1;this.Fd=this.Qc=!1;this.ug=this.A.xe();this.ba=new Map;this.za=new Set;this.Ic=!1;this.Nc="";this.ua=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.wf(b,c);this.Eb=null;
self.C3Audio_GetOutputStream=()=>this.rf();self.C3Audio_DOMInterface=this;B(this,[["create-audio-context",b=>this.Te(b)],["play",b=>this.Jf(b)],["stop",b=>this.fg(b)],["stop-all",()=>this.gg()],["set-paused",b=>this.Zf(b)],["set-volume",b=>this.dg(b)],["fade-volume",b=>this.Ye(b)],["set-master-volume",b=>this.Xf(b)],["set-muted",b=>this.Yf(b)],["set-silent",b=>this.ag(b)],["set-looping",b=>this.Wf(b)],["set-playback-rate",b=>this.$f(b)],["seek",b=>this.Qf(b)],["preload",b=>this.Kf(b)],["unload",b=>
this.kg(b)],["unload-all",()=>this.lg()],["set-suspended",b=>this.bg(b)],["add-effect",b=>this.ld(b)],["set-effect-param",b=>this.Tf(b)],["remove-effects",b=>this.Mf(b)],["tick",b=>this.Ff(b)],["load-state",b=>this.uf(b)]])}async Te(a){a.isiOSCordova&&(this.Qc=!0);this.Tc=a.timeScaleMode;this.Nd=["equalpower","HRTF","soundfield"][a.panningModel];this.Dd=["linear","inverse","exponential"][a.distanceModel];this.Od=a.refDistance;this.Md=a.maxDistance;this.Qd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.md();this.f.onstatechange=()=>{"running"!==this.f.state&&this.md()};this.Fb=this.f.createGain();this.Fb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.Yb();try{await Promise.all(a.preloadList.map(c=>
this.ub(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}md(){this.Hb||(this.Gc=!1,window.addEventListener("pointerup",this.na,!0),window.addEventListener("touchend",this.na,!0),window.addEventListener("click",this.na,!0),window.addEventListener("keydown",this.na,!0),this.Hb=!0)}Ve(){this.Hb&&(this.Gc=!0,window.removeEventListener("pointerup",this.na,!0),window.removeEventListener("touchend",this.na,!0),window.removeEventListener("click",
this.na,!0),window.removeEventListener("keydown",this.na,!0),this.Hb=!1)}jg(){if(!this.Gc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.Ve()}}U(){return this.f}Yb(){return this.f.currentTime}oa(){return this.Fb}bd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].N():this.oa()}Xd(a,b){a=a.toLowerCase();let c=this.ba.get(a);c||(c=[],this.ba.set(a,c));b.Vf(c.length);
b.cg(a);c.push(b);this.wd(a)}wd(a){let b=this.oa();const c=this.ba.get(a);if(c&&c.length){b=c[0].N();for(let f=0,p=c.length;f<p;++f){const t=c[f];f+1===p?t.P(this.oa()):t.P(c[f+1].N())}}for(const f of this.ja(a))f.Ee(b);this.ua&&this.Nc===a&&(this.ua.disconnect(),this.ua.connect(b))}mb(){return this.Mc}nb(){return this.la}Uf(){this.Fd=!0}oe(a,b){return b?this.A.mg(a).then(c=>{const f=this.f.createBuffer(1,c.length,48E3);f.getChannelData(0).set(c);return f}):new Promise((c,f)=>{this.f.decodeAudioData(a,
c,f)})}ra(a){this.A.ra(a)}xa(a){this.A.xa(a)}gd(a){let b=0;for(let c=0,f=this.C.length;c<f;++c){const p=this.C[c];this.C[b]=p;p.J===a?p.c():++b}this.C.length=b}Fe(){let a=0;for(let b=0,c=this.aa.length;b<c;++b){const f=this.aa[b];this.aa[a]=f;f.pa()?f.c():++a}this.aa.length=a}*ja(a){if(a)for(const b of this.C)self.da.pe(b.Z,a)&&(yield b);else this.ga&&!this.ga.R()&&(yield this.ga)}async ub(a,b,c,f,p){for(const t of this.aa)if(t.Ma()===b)return await Y(t),t;if(p)return null;f&&(this.Qc||this.Fd)&&
this.Fe();p="audio/webm; codecs=opus"===c&&!this.ug;f&&p&&this.Uf();a=!f||this.Qc||p?new self.ke(this,a,b,c,f,p):new self.ie(this,a,b,c,f);this.aa.push(a);await Y(a);return a}async mc(a,b,c,f,p){for(const t of this.C)if(t.Ma()===b&&(t.Vb()||p))return t.He(f),t;a=await this.ub(a,b,c,p);f="html5"===a.zc?new self.je(a.i,a,f):new self.le(a.i,a,f);this.C.push(f);return f}Le(a){let b=this.eb.get(a);if(!b){let c=null;b={Vc:0,promise:new Promise(f=>c=f),resolve:c};this.eb.set(a,b)}b.Vc++}Nf(a){const b=this.eb.get(a);
if(!b)throw Error("expected pending tag");b.Vc--;0===b.Vc&&(b.resolve(),this.eb.delete(a))}jc(a){a||(a=this.Kd);return(a=this.eb.get(a))?a.promise:Promise.resolve()}xb(){if(0<this.za.size)C(this);else for(const a of this.C)if(a.cd()){C(this);break}}qa(){for(var a of this.za)a.qa();a=this.Yb();for(var b of this.C)b.qa(a);b=this.C.filter(c=>c.cd()).map(c=>c.La());v(this,"state",{tickCount:this.Ld,audioInstances:b,analysers:[...this.za].map(c=>c.re())});0===b.length&&0===this.za.size&&this.Ib&&(this.A.Of(this.Td),
this.Ib=!1)}ec(a,b,c){v(this,"trigger",{type:a,tag:b,aiid:c})}async Jf(a){const b=a.originalUrl,c=a.url,f=a.type,p=a.isMusic,t=a.tag,d=a.isLooping,g=a.vol,n=a.pos,l=a.panning;let q=a.off;0<q&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),q=q-a.performanceTime/1E3+a.contextTime):q=q-performance.now()/1E3+this.f.currentTime);this.Kd=t;this.Le(t);try{this.ga=await this.mc(b,c,f,t,p),l?(this.ga.rb(!0),this.ga.Ge(l.x,l.y,l.angle,l.innerAngle,l.outerAngle,l.outerGain),l.hasOwnProperty("uid")&&
this.ga.Ie(l.uid)):this.ga.rb(!1),this.ga.Play(d,g,n,q)}catch(e){console.error("[Construct 3] Audio: error starting playback: ",e);return}finally{this.Nf(t)}C(this)}fg(a){a=a.tag;for(const b of this.ja(a))b.ka()}gg(){for(const a of this.C)a.ka()}Zf(a){const b=a.tag;a=a.paused;for(const c of this.ja(b))a?c.Na():c.pb();this.xb()}dg(a){const b=a.tag;a=a.vol;for(const c of this.ja(b))c.tb(a)}async Ye(a){const b=a.tag,c=a.vol,f=a.duration;a=a.stopOnEnd;await this.jc(b);for(const p of this.ja(b))p.qe(c,
f,a);this.xb()}Xf(a){this.Mc=a.vol;for(const b of this.C)b.Cb()}Yf(a){const b=a.tag;a=a.isMuted;for(const c of this.ja(b))c.hd(a)}ag(a){this.la=a.isSilent;this.A.sb(this.la);for(const b of this.C)b.Bb()}Wf(a){const b=a.tag;a=a.isLooping;for(const c of this.ja(b))c.hc(a)}async $f(a){const b=a.tag;a=a.rate;await this.jc(b);for(const c of this.ja(b))c.kd(a)}async Qf(a){const b=a.tag;a=a.pos;await this.jc(b);for(const c of this.ja(b))c.fc(a)}async Kf(a){const b=a.originalUrl,c=a.url,f=a.type;a=a.isMusic;
try{await this.mc(b,c,f,"",a)}catch(p){console.error("[Construct 3] Audio: error preloading: ",p)}}async kg(a){if(a=await this.ub("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}lg(){for(const a of this.aa)a.c();this.aa.length=0}bg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.C)b.ic(a);a&&this.f.suspend&&this.f.suspend()}Ff(a){this.Sb=a.timeScale;this.Ec=a.gameTime;this.Ld=a.tickCount;if(0!==this.Tc)for(var b of this.C)b.ya();(b=a.listenerPos)&&
this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const f of this.C)f.fa===a&&f.jd(c.x,c.y,c.angle)}}async ld(a){var b=a.type;const c=a.tag;var f=a.params;if("filter"===b)f=new self.ce(this,...f);else if("delay"===b)f=new self.ae(this,...f);else if("convolution"===b){b=null;try{b=await this.ub(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(p){console.log("[Construct 3] Audio: error loading convolution: ",p);return}f=new self.$d(this,b.$,...f);f.Rf(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)f=new self.de(this,...f);else if("phaser"===b)f=new self.fe(this,...f);else if("gain"===b)f=new self.ee(this,...f);else if("tremolo"===b)f=new self.he(this,...f);else if("ringmod"===b)f=new self.ge(this,...f);else if("distortion"===b)f=new self.be(this,...f);else if("compressor"===b)f=new self.Zd(this,...f);else if("analyser"===b)f=new self.Yd(this,...f);else throw Error("invalid effect type");this.Xd(c,f);this.vd()}Tf(a){const b=a.index,c=a.param,f=a.value,p=a.ramp,
t=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(c,f,p,t),this.vd())}Mf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const c of b)c.c();this.ba.delete(a);this.wd(a)}}Ke(a){this.za.add(a);this.xb()}Lf(a){this.za.delete(a)}vd(){this.Ic||(this.Ic=!0,Promise.resolve().then(()=>this.We()))}We(){const a={};for(const [b,c]of this.ba)a[b]=c.map(f=>f.La());v(this,"fxstate",{fxstate:a});this.Ic=!1}async uf(a){const b=a.saveLoadMode;if(3!==b)for(var c of this.C)c.pa()&&1===
b||(c.pa()||2!==b)&&c.ka();for(const f of this.ba.values())for(const p of f)p.c();this.ba.clear();this.Sb=a.timeScale;this.Ec=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.la=a.isSilent;this.A.sb(this.la);this.Mc=a.masterVolume;c=[];for(const f of Object.values(a.effects))c.push(Promise.all(f.map(p=>this.ld(p))));await Promise.all(c);await Promise.all(a.playing.map(f=>this.ef(f,b)));this.xb()}async ef(a,b){if(3!==b){var c=a.bufferOriginalUrl,f=a.bufferUrl,p=a.bufferType,
t=a.isMusic,d=a.tag,g=a.isLooping,n=a.volume,l=a.playbackTime;if(!t||1!==b)if(t||2!==b){b=null;try{b=await this.mc(c,f,p,d,t)}catch(q){console.error("[Construct 3] Audio: error loading audio state: ",q);return}b.Ce(a.pan);b.Play(g,n,l,0);a.isPlaying||b.Na();b.qc(a)}}}wf(a,b){this.ua&&this.ua.disconnect();this.Nc=b.toLowerCase();this.ua=this.f.createMediaStreamSource(a);this.ua.connect(this.bd(this.Nc))}rf(){this.Eb||(this.Eb=this.f.createMediaStreamDestination(),this.Fb.connect(this.Eb));return this.Eb.stream}static pe(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Je(a){return a*h}static ne(a){return Math.pow(10,a/20)}static ad(a){return Math.max(Math.min(self.da.ne(a),1),0)}static Be(a){return Math.log(a)/Math.log(10)*20}static Ae(a){return self.da.Be(Math.max(Math.min(a,1),0))}static wg(a,b){return 1-Math.exp(-b*a)}};self.qb.Ub(self.da)}"use strict";function Y(h){h.Kb||(h.Kb=h.pc());return h.Kb}
self.Yc=class{constructor(h,a,b,c,f){this.i=h;this.sg=a;this.va=b;this.O=c;this.pg=f;this.zc="";this.Kb=null}c(){this.Kb=this.i=null}pc(){}U(){return this.i.U()}$b(){return this.sg}Ma(){return this.va}Zb(){return this.O}pa(){return this.pg}ea(){}};"use strict";
self.ie=class extends self.Yc{constructor(h,a,b,c,f){super(h,a,b,c,f);this.zc="html5";this.H=new Audio;this.H.crossOrigin="anonymous";this.H.autoplay=!1;this.H.preload="auto";this.Ya=this.Za=null;this.H.addEventListener("canplaythrough",()=>!0);this.cb=this.U().createGain();this.ab=null;this.H.addEventListener("canplay",()=>{this.Za&&(this.Za(),this.Ya=this.Za=null);!this.ab&&this.H&&(this.ab=this.U().createMediaElementSource(this.H),this.ab.connect(this.cb))});this.onended=null;this.H.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.H.addEventListener("error",p=>{console.error(`[Construct 3] Audio '${this.va}' error: `,p);this.Ya&&(this.Ya(p),this.Ya=this.Za=null)})}c(){this.i.gd(this);this.cb.disconnect();this.cb=null;this.ab.disconnect();this.ab=null;this.H&&!this.H.paused&&this.H.pause();this.H=this.onended=null;super.c()}pc(){return new Promise((h,a)=>{this.Za=h;this.Ya=a;this.H.src=this.va})}M(){return this.H}ea(){return this.H.duration}};"use strict";
async function aa(h){if(h.sa)return h.sa;var a=h.i.A;if("cordova"===a.W&&a.ye(h.va)&&"file:"===location.protocol)h.sa=await a.Wb(h.va);else{a=await fetch(h.va);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);h.sa=await a.arrayBuffer()}}async function ba(h){if(h.$)return h.$;h.$=await h.i.oe(h.sa,h.rg);h.sa=null}
self.ke=class extends self.Yc{constructor(h,a,b,c,f,p){super(h,a,b,c,f);this.zc="webaudio";this.$=this.sa=null;this.rg=!!p}c(){this.i.gd(this);this.$=this.sa=null;super.c()}async pc(){try{await aa(this),await ba(this)}catch(h){console.error(`[Construct 3] Failed to load audio '${this.va}': `,h)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let h=0;self.Zc=class{constructor(a,b,c){this.i=a;this.J=b;this.Z=c;this.Db=h++;this.K=this.U().createGain();this.K.connect(this.oa());this.v=null;this.Wa=!1;this.F=!0;this.T=this.ia=this.D=!1;this.hb=1;this.Aa=!1;this.Y=1;a=this.i.Tc;this.Kc=1===a&&!this.pa()||2===a;this.Ta=this.fa=-1;this.Sd=!1}c(){this.J=this.i=null;this.v&&(this.v.disconnect(),this.v=null);this.K.disconnect();this.K=null}U(){return this.i.U()}oa(){return this.i.bd(this.Z)}mb(){return this.i.mb()}lb(){return this.Kc?this.i.Ec:
performance.now()/1E3}$b(){return this.J.$b()}Ma(){return this.J.Ma()}Zb(){return this.J.Zb()}pa(){return this.J.pa()}He(a){this.Z=a}R(){}Vb(){}IsPlaying(){return!this.F&&!this.D&&!this.R()}cd(){return!this.F&&!this.R()}wa(){}ea(){return this.J.ea()}Play(){}ka(){}Na(){}pb(){}tb(a){this.hb=a;this.K.gain.cancelScheduledValues(0);this.Ta=-1;this.K.gain.value=this.ac()}qe(a,b,c){if(!this.Aa){a*=this.mb();var f=this.K.gain;f.cancelScheduledValues(0);var p=this.i.Yb();b=p+b;f.setValueAtTime(f.value,p);
f.linearRampToValueAtTime(a,b);this.hb=a;this.Ta=b;this.Sd=c}}Cb(){this.tb(this.hb)}qa(a){-1!==this.Ta&&a>=this.Ta&&(this.Ta=-1,this.Sd&&this.ka(),this.i.ec("fade-ended",this.Z,this.Db))}ac(){const a=this.hb*this.mb();return isFinite(a)?a:0}hd(a){a=!!a;this.Aa!==a&&(this.Aa=a,this.Bb())}nb(){return this.i.nb()}Bb(){}hc(){}kd(a){this.Y!==a&&(this.Y=a,this.ya())}ya(){}fc(){}ic(){}rb(a){a=!!a;this.Wa!==a&&((this.Wa=a)?(this.v||(this.v=this.U().createPanner(),this.v.panningModel=this.i.Nd,this.v.distanceModel=
this.i.Dd,this.v.refDistance=this.i.Od,this.v.maxDistance=this.i.Md,this.v.rolloffFactor=this.i.Qd),this.K.disconnect(),this.K.connect(this.v),this.v.connect(this.oa())):(this.v.disconnect(),this.K.disconnect(),this.K.connect(this.oa())))}Ge(a,b,c,f,p,t){this.Wa&&(this.jd(a,b,c),a=self.da.Je,this.v.coneInnerAngle=a(f),this.v.coneOuterAngle=a(p),this.v.coneOuterGain=t)}jd(a,b,c){this.Wa&&(this.v.setPosition(a,b,0),this.v.setOrientation(Math.cos(c),Math.sin(c),0))}Ie(a){this.fa=a}bc(){}Ee(a){const b=
this.v||this.K;b.disconnect();b.connect(a)}La(){return{aiid:this.Db,tag:this.Z,duration:this.ea(),volume:this.hb,isPlaying:this.IsPlaying(),playbackTime:this.wa(),playbackRate:this.Y,uid:this.fa,bufferOriginalUrl:this.$b(),bufferUrl:"",bufferType:this.Zb(),isMusic:this.pa(),isLooping:this.T,isMuted:this.Aa,resumePosition:this.bc(),pan:this.se()}}qc(a){this.kd(a.playbackRate);this.hd(a.isMuted)}se(){if(!this.v)return null;const a=this.v;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Ce(a){a?(this.rb(!0),a=this.v,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.fa=a.uid):this.rb(!1)}}}"use strict";
self.je=class extends self.Zc{constructor(h,a,b){super(h,a,b);this.J.cb.connect(this.K);this.J.onended=()=>this.rc()}c(){this.ka();this.J.cb.disconnect();super.c()}M(){return this.J.M()}rc(){this.F=!0;this.fa=-1;this.i.ec("ended",this.Z,this.Db)}R(){return this.M().ended}Vb(){return this.F?!0:this.R()}wa(h){let a=this.M().currentTime;h&&(a*=this.Y);this.T||(a=Math.min(a,this.ea()));return a}Play(h,a,b){const c=this.M();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==h&&(c.loop=h);this.tb(a);c.muted&&
(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.J.Ma()}' to position '${b}': `,f)}this.i.ra(c);this.D=this.F=!1;this.T=h;this.Y=1}ka(){const h=this.M();h.paused||h.pause();this.i.xa(h);this.F=!0;this.D=!1;this.fa=-1}Na(){if(!(this.D||this.F||this.R())){var h=this.M();h.paused||h.pause();this.i.xa(h);this.D=!0}}pb(){!this.D||this.F||this.R()||(this.i.ra(this.M()),this.D=!1)}Bb(){this.M().muted=this.Aa||this.nb()}hc(h){h=!!h;
this.T!==h&&(this.T=h,this.M().loop=h)}ya(){let h=this.Y;this.Kc&&(h*=this.i.Sb);try{this.M().playbackRate=h}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${h}':`,a)}}fc(h){if(!this.F&&!this.R())try{this.M().currentTime=h}catch(a){console.warn(`[Construct 3] Error seeking audio to '${h}': `,a)}}bc(){return this.wa()}ic(h){h?this.IsPlaying()?(this.M().pause(),this.ia=!0):this.ia=!1:this.ia&&(this.i.ra(this.M()),this.ia=!1)}};"use strict";
function Z(h){h.j&&h.j.disconnect();h.j=null;h.Pa=null}
self.le=class extends self.Zc{constructor(h,a,b){super(h,a,b);this.j=null;this.Nb=c=>this.rc(c);this.Fc=!0;this.Pa=null;this.L=this.Rb=0;this.Oc=1}c(){this.ka();Z(this);this.Nb=null;super.c()}rc(h){this.D||this.ia||h.target!==this.Pa||(this.F=this.Fc=!0,this.fa=-1,Z(this),this.i.ec("ended",this.Z,this.Db))}R(){return!this.F&&this.j&&this.j.loop||this.D?!1:this.Fc}Vb(){return!this.j||this.F?!0:this.R()}wa(h){let a;a=this.D?this.L:this.lb()-this.Rb;h&&(a*=this.Y);this.T||(a=Math.min(a,this.ea()));return a}Play(h,
a,b,c){this.Oc=1;this.tb(a);Z(this);this.j=this.U().createBufferSource();this.j.buffer=this.J.$;this.j.connect(this.K);this.Pa=this.j;this.j.onended=this.Nb;this.j.loop=h;this.j.start(c,b);this.D=this.F=this.Fc=!1;this.T=h;this.Y=1;this.Rb=this.lb()-b}ka(){if(this.j)try{this.j.stop(0)}catch(h){}this.F=!0;this.D=!1;this.fa=-1}Na(){this.D||this.F||this.R()||(this.L=this.wa(!0),this.T&&(this.L%=this.ea()),this.D=!0,this.j.stop(0))}pb(){!this.D||this.F||this.R()||(Z(this),this.j=this.U().createBufferSource(),
this.j.buffer=this.J.$,this.j.connect(this.K),this.Pa=this.j,this.j.onended=this.Nb,this.j.loop=this.T,this.Cb(),this.ya(),this.Rb=this.lb()-this.L/(this.Y||.001),this.j.start(0,this.L),this.D=!1)}ac(){return super.ac()*this.Oc}Bb(){this.Oc=this.Aa||this.nb()?0:1;this.Cb()}hc(h){h=!!h;this.T!==h&&(this.T=h,this.j&&(this.j.loop=h))}ya(){let h=this.Y;this.Kc&&(h*=this.i.Sb);this.j&&(this.j.playbackRate.value=h)}fc(h){this.F||this.R()||(this.D?this.L=h:(this.Na(),this.L=h,this.pb()))}bc(){return this.L}ic(h){h?
this.IsPlaying()?(this.ia=!0,this.L=this.wa(!0),this.T&&(this.L%=this.ea()),this.j.stop(0)):this.ia=!1:this.ia&&(Z(this),this.j=this.U().createBufferSource(),this.j.buffer=this.J.$,this.j.connect(this.K),this.Pa=this.j,this.j.onended=this.Nb,this.j.loop=this.T,this.Cb(),this.ya(),this.Rb=this.lb()-this.L/(this.Y||.001),this.j.start(0,this.L),this.ia=!1)}qc(h){super.qc(h);this.L=h.resumePosition}};"use strict";
{class h{constructor(a){this.i=a;this.f=a.U();this.Gd=-1;this.O=this.Z="";this.g=null}c(){this.f=null}Vf(a){this.Gd=a}cg(a){this.Z=a}o(){return this.f.createGain()}N(){}P(){}m(a,b,c,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var p=this.f.currentTime;f+=p;switch(c){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,p);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,p),a.exponentialRampToValueAtTime(b,f)}}}La(){return{type:this.O,tag:this.Z,params:this.g}}}
self.ce=class extends h{constructor(a,b,c,f,p,t,d){super(a);this.O="filter";this.g=[b,c,f,p,t,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=f;this.u.Q.value=p;this.u.gain.vlaue=t;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}P(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,f);this.m(this.a.gain,1-b,c,f);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,f);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,f);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,f);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,f)}}};self.ae=class extends h{constructor(a,b,c,f){super(a);this.O="delay";this.g=[b,c,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.$a=this.o();this.S=this.f.createDelay(b);this.S.delayTime.value=b;this.Sa=this.o();this.Sa.gain.value=c;this.l.connect(this.$a);this.l.connect(this.a);this.$a.connect(this.b);this.$a.connect(this.S);this.S.connect(this.Sa);this.Sa.connect(this.$a)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.$a.disconnect();this.S.disconnect();this.Sa.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,b,c,f){const p=self.da.ad;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,f);this.m(this.a.gain,1-b,c,f);break;case 4:this.g[1]=p(b);this.m(this.Sa.gain,p(b),c,f);break;case 5:this.g[0]=b,this.m(this.S.delayTime,b,c,f)}}};self.$d=class extends h{constructor(a,b,c,f){super(a);this.O="convolution";this.g=[c,f];this.Bd=this.Ad="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.Ra=this.f.createConvolver();this.Ra.normalize=c;this.Ra.buffer=b;this.l.connect(this.Ra);this.l.connect(this.a);this.Ra.connect(this.b)}c(){this.l.disconnect();this.Ra.disconnect();this.b.disconnect();this.a.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,f),this.m(this.a.gain,1-b,c,f)}}Rf(a,b){this.Ad=a;this.Bd=b}La(){const a=
super.La();a.bufferOriginalUrl=this.Ad;a.bufferUrl="";a.bufferType=this.Bd;return a}};self.de=class extends h{constructor(a,b,c,f,p,t){super(a);this.O="flanger";this.g=[b,c,f,p,t];this.l=this.o();this.a=this.o();this.a.gain.value=1-t/2;this.b=this.o();this.b.gain.value=t/2;this.Ua=this.o();this.Ua.gain.value=p;this.S=this.f.createDelay(b+c);this.S.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=f;this.G=this.o();this.G.gain.value=c;this.l.connect(this.S);this.l.connect(this.a);
this.S.connect(this.b);this.S.connect(this.Ua);this.Ua.connect(this.S);this.s.connect(this.G);this.G.connect(this.S.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.S.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();this.Ua.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,f);this.m(this.a.gain,1-b/2,c,f);break;case 6:this.g[1]=b/1E3;this.m(this.G.gain,b/1E3,c,f);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,f);break;case 8:this.g[3]=b/100,this.m(this.Ua.gain,b/100,c,f)}}};self.fe=class extends h{constructor(a,b,c,f,p,t,d){super(a);this.O="phaser";this.g=[b,c,f,p,t,d];this.l=this.o();this.a=this.o();this.a.gain.value=1-d/2;this.b=this.o();this.b.gain.value=d/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=f;this.s=this.f.createOscillator();this.s.frequency.value=t;this.G=this.o();this.G.gain.value=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.G);this.G.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,
b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,f);this.m(this.a.gain,1-b/2,c,f);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,f);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,f);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,f);break;case 6:this.g[3]=b;this.m(this.G.gain,b,c,f);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,f)}}};self.ee=class extends h{constructor(a,b){super(a);this.O="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}X(a,b,c,f){const p=self.da.ad;switch(a){case 4:this.g[0]=p(b),this.m(this.h.gain,p(b),c,f)}}};self.he=class extends h{constructor(a,b,c){super(a);this.O="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.G=this.o();this.G.gain.value=c/2;this.s.connect(this.G);this.G.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.G.disconnect();this.h.disconnect();super.c()}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain.value,1-b/2,c,f);this.m(this.G.gain.value,b/2,c,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,f)}}};self.ge=class extends h{constructor(a,b,c){super(a);this.O="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.gb=this.o();
this.gb.gain.value=0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.gb.gain);this.s.start(0);this.l.connect(this.gb);this.l.connect(this.a);this.gb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.gb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}P(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,
b,c,f);this.m(this.a.gain,1-b,c,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,f)}}};self.be=class extends h{constructor(a,b,c,f,p,t){super(a);this.O="distortion";this.g=[b,c,f,p,t];this.l=this.o();this.Pb=this.o();this.Ob=this.o();this.Sf(f,p);this.b=this.o();this.b.gain.value=t;this.a=this.o();this.a.gain.value=1-t;this.Tb=this.f.createWaveShaper();this.Cc=new Float32Array(65536);this.$e(b,c);this.Tb.curve=this.Cc;this.l.connect(this.Pb);this.l.connect(this.a);this.Pb.connect(this.Tb);
this.Tb.connect(this.Ob);this.Ob.connect(this.b)}c(){this.l.disconnect();this.Pb.disconnect();this.Tb.disconnect();this.Ob.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Sf(a,b){.01>a&&(a=.01);this.Pb.gain.value=a;this.Ob.gain.value=Math.pow(1/a,.6)*b}$e(a,b){for(let c=0;32768>c;++c){let f=c/32768;f=this.eg(f,a,b);this.Cc[32768+c]=f;this.Cc[32768-c-1]=-f}}eg(a,b,c){c=1.05*c*b-b;const f=0>a?-a:a;return(f<b?f:b+c*self.da.wg(f-b,1/c))*(0>a?-1:1)}P(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}N(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,f),this.m(this.a.gain,1-b,c,f)}}};self.Zd=class extends h{constructor(a,b,c,f,p,t){super(a);this.O="compressor";this.g=[b,c,f,p,t];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=f;this.h.attack.value=p;this.h.release.value=t}c(){this.h.disconnect();super.c()}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}X(){}};
self.Yd=class extends h{constructor(a,b,c){super(a);this.O="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Ed=new Float32Array(this.h.frequencyBinCount);this.Rd=new Uint8Array(b);this.Pd=this.Da=0;this.i.Ke(this)}c(){this.i.Lf(this);this.h.disconnect();super.c()}qa(){this.h.getFloatFrequencyData(this.Ed);this.h.getByteTimeDomainData(this.Rd);const a=this.h.fftSize;let b=this.Da=0;for(var c=0;c<a;++c){let f=(this.Rd[c]-128)/128;0>f&&(f=-f);
this.Da<f&&(this.Da=f);b+=f*f}c=self.da.Ae;this.Da=c(this.Da);this.Pd=c(Math.sqrt(b/a))}P(a){this.h.disconnect();this.h.connect(a)}N(){return this.h}X(){}re(){return{tag:this.Z,index:this.Gd,peak:this.Da,rms:this.Pd,binCount:this.h.frequencyBinCount,freqBins:this.Ed}}}};