'use strict';function r(n,f,g,p){n.f.W(n.A,f,g,p,void 0)}function w(n,f,g,p){n.f.s?r(n,f,g,p):n.f.ob()._OnMessageFromDOM({type:"event",component:n.A,handler:f,dispatchOpts:p||null,data:g,responseId:null})}function z(n,f,g){n.f.a(n.A,f,g)}function B(n,f){for(const [g,p]of f)z(n,g,p)}window.U=class{constructor(n,f){this.f=n;this.A=f;this.Oa=!1;this.Zb=()=>this.Aa()}va(){}Aa(){}};
window.bb=class{constructor(n,f){this.Ma=n;this.Ub=f;this.o=-1;this.P=-Infinity;this.$b=()=>{this.o=-1;this.P=Date.now();this.B=!0;this.Ma();this.B=!1};this.Na=this.B=!1}};"use strict";function C(n,f){z(n,"get-element",g=>{const p=n.h.get(g.elementId);return f(p,g)})}
window.mc=class extends self.U{constructor(n,f){super(n,f);this.h=new Map;this.ha=!0;B(this,[["create",()=>{throw Error("required override");}],["destroy",g=>{{g=g.elementId;const p=this.h.get(g);this.ha&&p.parentElement.removeChild(p);this.h.delete(g)}}],["set-visible",g=>{this.ha&&(this.h.get(g.elementId).style.display=g.isVisible?"":"none")}],["update-position",g=>{if(this.ha){var p=this.h.get(g.elementId);p.style.left=g.left+"px";p.style.top=g.top+"px";p.style.width=g.width+"px";p.style.height=
g.height+"px";g=g.fontSize;null!==g&&(p.style.fontSize=g+"em")}}],["update-state",g=>{this.h.get(g.elementId);throw Error("required override");}],["focus",g=>{{const p=this.h.get(g.elementId);g.focus?p.focus():p.blur()}}],["set-css-style",g=>{this.h.get(g.elementId).style[g.prop]=g.val}],["set-attribute",g=>{this.h.get(g.elementId).setAttribute(g.name,g.val)}],["remove-attribute",g=>{this.h.get(g.elementId).removeAttribute(g.name)}]]);C(this,g=>g)}};"use strict";
{var D=function(m){return k.has(m)},E=function(m){return new Promise((b,d)=>{const e=new FileReader;e.onload=l=>b(l.target.result);e.onerror=l=>d(l);e.readAsArrayBuffer(m)})},F=async function(m){m=await E(m);return(new TextDecoder("utf-8")).decode(m)},G=function(m){if(m.cc){const b=document.createElement("script");b.async=!1;b.textContent=m.fc;document.head.appendChild(b)}else return new Promise((b,d)=>{const e=document.createElement("script");e.onload=b;e.onerror=d;e.async=!1;e.src=m;document.head.appendChild(e)})};
const n=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let f=new Audio;const g={"audio/webm; codecs=opus":!!f.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!f.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!f.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!f.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!f.canPlayType("audio/mp4"),"audio/mpeg":!!f.canPlayType("audio/mpeg")};f=null;const p=[];let u=0;window.RealFile=
window.File;const A=[],y=new Map,a=new Map;let c=0;const h=[];self.rc=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");h.push(m)};const k=new Set(["cordova","playable-ad","instant-games"]);window.X=class m{constructor(b){this.s=b.ic;this.D=null;this.b="";this.ra=b.ec;this.H={};this.ma=this.Ta=null;this.O=[];this.C=this.c=this.qa=null;this.l=-1;this.Yb=()=>this.Hb();this.pa=[];this.g=b.Ua;D(this.g)&&this.s&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.s=!1);this.Sa=!1;this.R=this.i=null;"html5"!==this.g&&"playable-ad"!==this.g||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.a("runtime","cordova-fetch-local-file",d=>this.vb(d));this.a("runtime","create-job-worker",()=>this.wb());"cordova"===this.g?document.addEventListener("deviceready",()=>this.Ea(b)):this.Ea(b)}ya(){return n&&"cordova"===
this.g}I(){return n&&D(this.g)||navigator.standalone}async Ea(b){if("playable-ad"===this.g){this.i=self.c3_base64files;this.R={};await this.jb();for(let e=0,l=b.u.length;e<l;++e){var d=b.u[e].toLowerCase();this.R.hasOwnProperty(d)?b.u[e]={cc:!0,fc:this.R[d]}:this.i.hasOwnProperty(d)&&(b.u[e]=URL.createObjectURL(this.i[d]))}}b.ac?this.b=b.ac:(d=location.origin,this.b=("null"===d?"file:///":d)+location.pathname,d=this.b.lastIndexOf("/"),-1!==d&&(this.b=this.b.substr(0,d+1)));if(b.kc)for(const [e,l]of Object.entries(b.kc))this.H[e]=
URL.createObjectURL(l);d=new MessageChannel;this.D=d.port1;this.D.onmessage=e=>this._OnMessageFromRuntime(e.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(e=>this.Eb(e));this.C=new self.$a(this);await this.C.Za();this.za();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this.Rb();this.s?await this.qb(b,d.port2):await this.pb(b,d.port2)}Z(b){return this.H.hasOwnProperty(b)?
this.H[b]:b.endsWith("/workermain.js")&&this.H.hasOwnProperty("workermain.js")?this.H["workermain.js"]:"playable-ad"===this.g&&this.i.hasOwnProperty(b.toLowerCase())?URL.createObjectURL(this.i[b.toLowerCase()]):b}async T(b,d,e){if(b.startsWith("blob:"))return new Worker(b,e);if(this.ya()&&"file:"===location.protocol)return b=await this.xa(this.ra+b),new Worker(URL.createObjectURL(new Blob([b],{type:"application/javascript"})),e);b=new URL(b,d);if(location.origin!==b.origin){b=await fetch(b);if(!b.ok)throw Error("failed to fetch worker script");
b=await b.blob();return new Worker(URL.createObjectURL(b),e)}return new Worker(b,e)}za(){if(this.I()){const b=document.documentElement.style,d=document.body.style,e=window.innerWidth<window.innerHeight,l=e?window.screen.width:window.screen.height;d.height=b.height=(e?window.screen.height:window.screen.width)+"px";d.width=b.width=l+"px"}}Da(b){return{baseUrl:this.b,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:m.V(),projectData:b.qc,
previewImageBlobs:window.cr_previewImageBlobs||this.i,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:b.Ua,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.pc,jobScheduler:this.C.Xa(),supportedAudioFormats:g,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ra+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ra+"opus.wasm.wasm",isiOSCordova:this.ya(),isiOSWebView:this.I(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async qb(b,d){var e=
this.Z(b.jc);this.Ta=await this.T(e,this.b,{name:"Runtime"});this.c=document.createElement("canvas");this.c.style.display="none";e=this.c.transferControlToOffscreen();document.body.appendChild(this.c);window.c3canvas=this.c;this.Ta.postMessage(Object.assign(this.Da(b),{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:e,workerDependencyScripts:b.ta||[],engineScripts:b.u,projectScripts:window.oc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,e,...this.C.Ya()]);this.O=A.map(l=>new l(this));
this.Ca();self.c3_callFunction=(l,q)=>this.qa.rb(l,q);"preview"===this.g&&(self.goToLastErrorScript=()=>this.W("runtime","go-to-last-error-script"))}async pb(b,d){this.c=document.createElement("canvas");this.c.style.display="none";document.body.appendChild(this.c);window.c3canvas=this.c;this.O=A.map(l=>new l(this));this.Ca();const e=b.u.map(l=>"string"===typeof l?(new URL(l,this.b)).toString():l);Array.isArray(b.ta)&&e.unshift(...b.ta);await Promise.all(e.map(l=>G(l)));if(b.Va&&0<b.Va.length){const l=
self.C3_ProjectScriptsStatus;try{if(await Promise.all(b.Va.map(q=>G(q[1]))),Object.values(l).some(q=>!q)){self.setTimeout(()=>this.Ja(l),100);return}}catch(q){console.error("[Preview] Error loading project scripts: ",q);self.setTimeout(()=>this.Ja(l),100);return}}"preview"===this.g&&"object"!==typeof self.lc.nc?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(b=Object.assign(this.Da(b),{isInWorker:!1,messagePort:d,canvas:this.c,runOnStartupFunctions:h}),this.ma=self.C3_CreateRuntime(b),await self.C3_InitRuntime(this.ma,b))}Ja(b){b=`Failed to load project script '${Object.entries(b).filter(d=>!d[1]).map(d=>d[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+b);alert(b)}async wb(){const b=await this.C.Ba();return{outputPort:b,transferables:[b]}}ob(){if(this.s)throw Error("not available in worker mode");return this.ma}W(b,
d,e,l,q){this.D.postMessage({type:"event",component:b,handler:d,dispatchOpts:l||null,data:e,responseId:null},this.Sa?void 0:q)}ab(b,d){const e=c++,l=new Promise((q,v)=>{a.set(e,{resolve:q,reject:v})});this.D.postMessage({type:"event",component:b,handler:"js-invoke-function",dispatchOpts:null,data:d,responseId:e},void 0);return l}["_OnMessageFromRuntime"](b){const d=b.type;if("event"===d)return this.Bb(b);if("result"===d)this.Kb(b);else if("runtime-ready"===d)this.Lb();else if("alert"===d)alert(b.message);
else throw Error(`unknown message '${d}'`);}Bb(b){const d=b.component,e=b.handler,l=b.data,q=b.responseId;if(b=y.get(d))if(b=b.get(e)){var v=null;try{v=b(l)}catch(t){console.error(`Exception in '${d}' handler '${e}':`,t);null!==q&&this.M(q,!1,""+t);return}if(null===q)return v;v&&v.then?v.then(t=>this.M(q,!0,t)).catch(t=>{console.error(`Rejection from '${d}' handler '${e}':`,t);this.M(q,!1,""+t)}):this.M(q,!0,v)}else console.warn(`[DOM] No handler '${e}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}M(b,
d,e){let l;e&&e.transferables&&(l=e.transferables);this.D.postMessage({type:"result",responseId:b,isOk:d,result:e},l)}Kb(b){const d=b.responseId,e=b.isOk;b=b.result;const l=a.get(d);e?l.resolve(b):l.reject(b);a.delete(d)}a(b,d,e){let l=y.get(b);l||(l=new Map,y.set(b,l));if(l.has(d))throw Error(`[DOM] Component '${b}' already has handler '${d}'`);l.set(d,e)}static ua(b){if(A.includes(b))throw Error("DOM handler already added");A.push(b)}Ca(){for(const b of this.O)if("runtime"===b.A){this.qa=b;return}throw Error("cannot find runtime DOM handler");
}Eb(b){this.W("debugger","message",b)}Lb(){for(const b of this.O)b.va()}static V(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}cb(b){this.pa.push(b);this.ga()}ga(){-1===this.l&&this.pa.length&&(this.l=requestAnimationFrame(this.Yb))}hb(){-1!==this.l&&(cancelAnimationFrame(this.l),this.l=-1)}Hb(){this.l=-1;for(const b of this.pa)b();this.ga()}fa(){this.qa.fa()}async vb(b){const d=b.filename;switch(b.as){case "text":return await this.Wa(d);case "buffer":return await this.xa(d);
default:throw Error("unsupported type");}}wa(b){const d=window.cordova.file.applicationDirectory+"www/"+b.toLowerCase();return new Promise((e,l)=>{window.resolveLocalFileSystemURL(d,q=>{q.file(e,l)},l)})}async Wa(b){b=await this.wa(b);return await F(b)}Y(){if(p.length&&!(8<=u)){u++;var b=p.shift();this.kb(b.filename,b.hc,b.bc)}}xa(b){return new Promise((d,e)=>{p.push({filename:b,hc:l=>{u--;this.Y();d(l)},bc:l=>{u--;this.Y();e(l)}});this.Y()})}async kb(b,d,e){try{const l=await this.wa(b),q=await E(l);
d(q)}catch(l){e(l)}}async jb(){const b=[];for(const [d,e]of Object.entries(this.i))b.push(this.ib(d,e));await Promise.all(b)}async ib(b,d){if("object"===typeof d)this.i[b]=new Blob([d.str],{type:d.type}),this.R[b]=d.str;else{let e=await this.nb(d);e||(e=this.lb(d));this.i[b]=e}}async nb(b){try{return await (await fetch(b)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
d),null}}lb(b){b=this.Pb(b);return this.gb(b.data,b.dc)}Pb(b){var d=b.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var e=b.substring(d+1);d=b.substring(5,d).split(";");b=d[0]||"";const l=d[2];e="base64"===d[1]||"base64"===l?atob(e):decodeURIComponent(e);return{dc:b,data:e}}gb(b,d){var e=b.length;let l=e>>2,q=new Uint8Array(e),v=new Uint32Array(q.buffer,0,l),t,x;for(x=t=0;t<l;++t)v[t]=b.charCodeAt(x++)|b.charCodeAt(x++)<<8|b.charCodeAt(x++)<<16|b.charCodeAt(x++)<<24;for(e&=
3;e--;)q[x]=b.charCodeAt(x),++x;return new Blob([q],{type:d})}Rb(){let b=null;const d=new Promise(q=>b=q),e=new ArrayBuffer(1),l=new MessageChannel;l.port2.onmessage=q=>{q.data&&q.data.arrayBuffer||(this.Sa=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));b()};l.port1.postMessage({arrayBuffer:e},[e]);return d}}}"use strict";
{var I=function(){const a=document.activeElement;if(!a)return!1;const c=a.tagName.toLowerCase(),h=new Set("email number password search tel text url".split(" "));return"textarea"===c?!0:"input"===c?h.has(a.type.toLowerCase()||"text"):H(a)},J=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(a){return!1}},K=function(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()},L=function(a){A.has(a.target.tagName.toLowerCase())&&a.preventDefault()},H=function(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;
a=a.parentNode}while(a);return!1},O=async function(a,c,h){if(!/firefox/i.test(navigator.userAgent))return await M(a);var k=await N(a);k=(new DOMParser).parseFromString(k,"image/svg+xml");const m=k.documentElement;if(m.hasAttribute("width")&&m.hasAttribute("height")){const b=m.getAttribute("width"),d=m.getAttribute("height");if(!b.includes("%")&&!d.includes("%"))return await M(a)}m.setAttribute("width",c+"px");m.setAttribute("height",h+"px");k=(new XMLSerializer).serializeToString(k);a=new Blob([k],
{type:"image/svg+xml"});return await M(a)},N=function(a){return new Promise((c,h)=>{let k=new FileReader;k.onload=m=>c(m.target.result);k.onerror=m=>h(m);k.readAsText(a)})},M=async function(a){a=URL.createObjectURL(a);try{return await P(a)}finally{URL.revokeObjectURL(a)}},P=function(a){return new Promise((c,h)=>{const k=new Image;k.onload=()=>c(k);k.onerror=m=>h(m);k.src=a})},Q=function(a){return new Promise((c,h)=>{const k=document.createElement("link");k.onload=()=>c(k);k.onerror=m=>h(m);k.rel=
"stylesheet";k.href=a;document.head.appendChild(k)})},R=function(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents};const n=self.X,f=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),g={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},p={dispatchUserScriptEvent:!0},u={dispatchRuntimeEvent:!0},A=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(a){a=
await M(a);if(0<a.width&&0<a.height)return[a.width,a.height];{a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const c=a.getBoundingClientRect();document.body.removeChild(a);return[c.width,c.height]}};self.C3_RasterSvgImageBlob=async function(a,c,h,k,m){a=await O(a,c,h);const b=document.createElement("canvas");b.width=k;b.height=m;b.getContext("2d").drawImage(a,0,0,c,h);return b};let y=!1;document.addEventListener("pause",()=>
y=!0);document.addEventListener("resume",()=>y=!1);n.ua(class extends self.U{constructor(a){super(a,"runtime");this.Pa=!0;this.m=-1;this.sa="any";this.Ka=this.La=!1;this.la=this.G=this.j=null;a.a("canvas","update-size",k=>this.Nb(k));a.a("runtime","invoke-download",k=>this.Db(k));a.a("runtime","raster-svg-image",k=>this.Ib(k));a.a("runtime","get-svg-image-size",k=>this.Cb(k));a.a("runtime","set-target-orientation",k=>this.Mb(k));a.a("runtime","register-sw",()=>this.Jb());a.a("runtime","post-to-debugger",
k=>this.Ha(k));a.a("runtime","go-to-script",k=>this.Ha(k));a.a("runtime","before-start-ticking",()=>this.ub());a.a("runtime","debug-highlight",k=>this.xb(k));a.a("runtime","enable-device-orientation",()=>this.fb());a.a("runtime","enable-device-motion",()=>this.eb());a.a("runtime","add-stylesheet",k=>this.sb(k));a.a("runtime","alert",k=>this.tb(k));const c=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const m=k.target;c.has(m.tagName.toLowerCase())||H(m)||k.preventDefault()});
const h=a.c;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);h.addEventListener("selectstart",L);h.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),h.addEventListener("pointerdown",L)):h.addEventListener("touchstart",L);this.F=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",
K,{passive:!1});window.addEventListener("wheel",K,{passive:!1});window.addEventListener("resize",()=>this.Ob());a.I()&&window.addEventListener("focusout",()=>{I()||(document.scrollingElement.scrollTop=0)});this.na=new Set;this.Xb=new WeakSet;this.Vb=!1}ub(){"cordova"===this.f.g?(document.addEventListener("pause",()=>this.ea(!0)),document.addEventListener("resume",()=>this.ea(!1))):document.addEventListener("visibilitychange",()=>this.ea(document.hidden));return{isSuspended:!(!document.hidden&&!y)}}va(){window.addEventListener("focus",
()=>this.N("window-focus"));window.addEventListener("blur",()=>{this.N("window-blur",{parentHasFocus:J()});this.F=0});window.addEventListener("fullscreenchange",()=>this.aa());window.addEventListener("webkitfullscreenchange",()=>this.aa());window.addEventListener("mozfullscreenchange",()=>this.aa());window.addEventListener("fullscreenerror",c=>this.ba(c));window.addEventListener("webkitfullscreenerror",c=>this.ba(c));window.addEventListener("mozfullscreenerror",c=>this.ba(c));window.addEventListener("keydown",
c=>this.Ga("keydown",c));window.addEventListener("keyup",c=>this.Ga("keyup",c));window.addEventListener("dblclick",c=>this.ca("dblclick",c,g));window.addEventListener("wheel",c=>this.Fb(c));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",c=>{this.$(c);this.v("pointerdown",c)}),this.f.s&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.G=new self.bb(()=>this.mb(),5),this.G.Na=!0,window.addEventListener("pointerrawupdate",c=>this.Gb(c))):window.addEventListener("pointermove",
c=>this.v("pointermove",c)),window.addEventListener("pointerup",c=>this.v("pointerup",c)),window.addEventListener("pointercancel",c=>this.v("pointercancel",c))):(window.addEventListener("mousedown",c=>{this.$(c);this.da("pointerdown",c)}),window.addEventListener("mousemove",c=>this.da("pointermove",c)),window.addEventListener("mouseup",c=>this.da("pointerup",c)),window.addEventListener("touchstart",c=>{this.$(c);this.L("pointerdown",c)}),window.addEventListener("touchmove",c=>this.L("pointermove",
c)),window.addEventListener("touchend",c=>this.L("pointerup",c)),window.addEventListener("touchcancel",c=>this.L("pointercancel",c)));const a=()=>this.fa();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);window.addEventListener("keydown",a,!0);window.addEventListener("gamepadconnected",a,!0)}N(a,c){r(this,a,c||null,u)}K(){return Math.max(window.innerWidth,1)}J(){return Math.max(window.innerHeight,1)}Ob(){const a=this.K(),c=this.J();
this.N("window-resize",{innerWidth:a,innerHeight:c,devicePixelRatio:window.devicePixelRatio});this.f.I()&&(-1!==this.m&&clearTimeout(this.m),this.Ia(a,c,0))}Qb(a,c,h){-1!==this.m&&clearTimeout(this.m);this.m=setTimeout(()=>this.Ia(a,c,h),48)}Ia(a,c,h){const k=this.K(),m=this.J();this.m=-1;k!=a||m!=c?this.N("window-resize",{innerWidth:k,innerHeight:m,devicePixelRatio:window.devicePixelRatio}):10>h&&this.Qb(k,m,h+1)}Mb(a){this.sa=a.targetOrientation}Sb(){const a=this.sa;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(c=>
console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(a):screen.webkitLockOrientation?c=screen.webkitLockOrientation(a):screen.mozLockOrientation?c=screen.mozLockOrientation(a):screen.msLockOrientation&&(c=screen.msLockOrientation(a));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",c)}}aa(){const a=n.V();a&&"any"!==this.sa&&this.Sb();r(this,"fullscreenchange",
{isFullscreen:a,innerWidth:this.K(),innerHeight:this.J()})}ba(a){console.warn("[Construct 3] Fullscreen request failed: ",a);r(this,"fullscreenerror",{isFullscreen:n.V(),innerWidth:this.K(),innerHeight:this.J()})}ea(a){a?this.f.hb():this.f.ga();r(this,"visibilitychange",{hidden:a})}Ga(a,c){"Backspace"===c.key&&L(c);const h=f.get(c.code)||c.code;w(this,a,{code:h,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},g)}Fb(a){r(this,
"wheel",{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},g)}ca(a,c,h){R(c)||w(this,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,timeStamp:c.timeStamp},h)}da(a,c){if(!R(c)){var h=this.F;"pointerdown"===a&&0!==h?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");w(this,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,
lastButtons:h,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},g);this.F=c.buttons;this.ca(c.type,c,p)}}v(a,c){if(this.G&&"pointermove"!==a){var h=this.G;h.B||(-1!==h.o&&(self.clearTimeout(h.o),h.o=-1),h.P=Date.now())}h=0;"mouse"===c.pointerType&&(h=this.F);w(this,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:h,clientX:c.clientX,clientY:c.clientY,
pageX:c.pageX,pageY:c.pageY,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},g);"mouse"===c.pointerType&&(h="mousemove","pointerdown"===a?h="mousedown":"pointerup"===a&&(h="pointerup"),this.ca(h,c,p),this.F=c.buttons)}Gb(a){this.la=a;a=this.G;if(-1===a.o){var c=Date.now(),h=c-a.P,k=a.Ub;h>=k&&a.Na?(a.P=c,a.B=!0,a.Ma(),a.B=!1):a.o=self.setTimeout(a.$b,Math.max(k-h,4))}}mb(){this.v("pointermove",
this.la);this.la=null}L(a,c){for(let h=0,k=c.changedTouches.length;h<k;++h){const m=c.changedTouches[h];w(this,a,{pointerId:m.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:m.clientX,clientY:m.clientY,pageX:m.pageX,pageY:m.pageY,width:2*(m.radiusX||m.webkitRadiusX||0),height:2*(m.radiusY||m.webkitRadiusY||0),pressure:m.force||m.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:m.rotationAngle||0,timeStamp:c.timeStamp},g)}}$(a){window!==window.top&&window.focus();this.Fa(a.target)&&
document.activeElement&&!this.Fa(document.activeElement)&&document.activeElement.blur()}Fa(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}fb(){this.La||(this.La=!0,window.addEventListener("deviceorientation",a=>this.zb(a)),window.addEventListener("deviceorientationabsolute",a=>this.Ab(a)))}eb(){this.Ka||(this.Ka=!0,window.addEventListener("devicemotion",a=>this.yb(a)))}zb(a){r(this,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||
0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},g)}Ab(a){r(this,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},g)}yb(a){let c=null;var h=a.acceleration;h&&(c={x:h.x||0,y:h.y||0,z:h.z||0});h=null;var k=a.accelerationIncludingGravity;k&&(h={x:k.x||0,y:k.y||0,z:k.z||0});k=null;const m=a.rotationRate;m&&(k={alpha:m.alpha||0,beta:m.beta||0,gamma:m.gamma||
0});r(this,"devicemotion",{acceleration:c,accelerationIncludingGravity:h,rotationRate:k,interval:a.interval,timeStamp:a.timeStamp},g)}Nb(a){const c=this.f,h=c.c;h.style.width=a.styleWidth+"px";h.style.height=a.styleHeight+"px";h.style.marginLeft=a.marginLeft+"px";h.style.marginTop=a.marginTop+"px";c.za();this.Pa&&(h.style.display="",this.Pa=!1)}Db(a){const c=a.url;a=a.filename;const h=document.createElement("a"),k=document.body;h.textContent=a;h.href=c;h.download=a;k.appendChild(h);h.click();k.removeChild(h)}async Ib(a){var c=
a.imageBitmapOpts;a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);c=c?await createImageBitmap(a,c):await createImageBitmap(a);return{imageBitmap:c,transferables:[c]}}async Cb(a){return await self.C3_GetSvgImageSize(a.blob)}async sb(a){await Q(a.url)}fa(){var a=[...this.na];this.na.clear();if(!this.Vb)for(const c of a)(a=c.play())&&a.catch(()=>{this.Xb.has(c)||this.na.add(c)})}xb(a){if(a.show){this.j||(this.j=document.createElement("div"),this.j.id=
"inspectOutline",document.body.appendChild(this.j));var c=this.j;c.style.display="";c.style.left=a.left-1+"px";c.style.top=a.top-1+"px";c.style.width=a.width+2+"px";c.style.height=a.height+2+"px";c.textContent=a.name}else this.j&&(this.j.style.display="none")}Jb(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ha(a){window.c3_postToMessagePort&&(a.from="runtime",window.c3_postToMessagePort(a))}rb(a,c){return this.f.ab(this.A,{name:a,params:c})}tb(a){alert(a.message)}})}"use strict";
{const n=document.currentScript.src;self.$a=class{constructor(f){this.S=f;this.b=n?n.substr(0,n.lastIndexOf("/")+1):f.b;this.Wb=Math.min(navigator.hardwareConcurrency||2,16);this.ia=null;this.Ra=[];this.oa=this.ja=null}async Za(){if(this.Tb)throw Error("already initialised");this.Tb=!0;var f=this.S.Z("dispatchworker.js");this.ia=await this.S.T(f,this.b,{name:"DispatchWorker"});f=new MessageChannel;this.ja=f.port1;this.ia.postMessage({type:"_init","in-port":f.port2},[f.port2]);this.oa=await this.Ba()}async Ba(){const f=
this.Ra.length;var g=this.S.Z("jobworker.js");g=await this.S.T(g,this.b,{name:"JobWorker"+f});const p=new MessageChannel,u=new MessageChannel;this.ia.postMessage({type:"_addJobWorker",port:p.port1},[p.port1]);g.postMessage({type:"init",number:f,"dispatch-port":p.port2,"output-port":u.port2},[p.port2,u.port2]);this.Ra.push(g);return u.port1}Xa(){return{inputPort:this.ja,outputPort:this.oa,maxNumWorkers:this.Wb}}Ya(){return[this.ja,this.oa]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.X({ic:"undefined"!==typeof OffscreenCanvas,jc:"workermain.js",u:["scripts/c3runtime.js"],ec:"scripts/",ta:[],Ua:"html5"}));"use strict";async function S(n){var f=T(n.index);if(f&&(f=f.vibrationActuator)&&f.playEffect)try{await f.playEffect("dual-rumble",{duration:n.duration,startDelay:0,weakMagnitude:n.weakMag,strongMagnitude:n.strongMag})}catch(g){console.warn("[Gamepad] Failed to vibrate gamepad: ",g)}}
function V(){return Array.from(navigator.getGamepads()).filter(n=>n&&n.connected)}function T(n){for(const f of V())if(f.index===n)return f;return null}
self.X.ua(class extends self.U{constructor(n){super(n,"gamepad");this.Qa=!!navigator.getGamepads;this.ka=!1;z(this,"is-supported",()=>this.Qa);z(this,"ready",()=>{this.ka=!0;for(const f of V())r(this,"gamepad-connected",{index:f.index,id:f.id});this.Qa&&!this.Oa&&(this.f.cb(this.Zb),this.Oa=!0)});z(this,"vibrate",f=>S(f));z(this,"reset-vibrate",f=>{(f=T(f.index))&&(f=f.vibrationActuator)&&f.reset&&f.reset()});window.addEventListener("gamepadconnected",f=>{this.ka&&(f=f.gamepad,r(this,"gamepad-connected",
{index:f.index,id:f.id}))});window.addEventListener("gamepaddisconnected",f=>{this.ka&&r(this,"gamepad-disconnected",{index:f.gamepad.index})});window.addEventListener("unload",()=>{for(const f of V()){const g=f.vibrationActuator;g&&g.reset&&g.reset()}})}Aa(){var n=V();n.length&&(n=n.map(f=>({index:f.index,id:f.id,buttons:f.buttons.map(g=>({pressed:g.pressed,value:g.value})),axes:f.axes})),r(this,"input-update",n))}});